### ISSUE TITLE
Error: Cannot parse releases feed: Error: Unable to find latest version on GitHub (https://api.github.co...

### ISSUE THREAD

**Issue by morajabi** [therepm/there-desktop#7]
https://sentry.io/there/desktop/issues/501249543/

```
Error: Cannot parse releases feed: Error: Unable to find latest version on GitHub (https://api.github.com/repos/therepm/there-desktop/releases/latest), please ensure a production release exists: HttpError: 403 Forbidden
{
  "message": "API rate limit exceeded for 162.245.20.51. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)",
  "documentation_url": "https://developer.github.com/v3/#rate-limiting"
}
Headers: {
  "access-control-allow-origin": [
    "*"
  ],
  "access-control-expose-headers": [
    "ETag, Link, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval"
  ],
  "content-encoding": [
    "gzip"
  ],
  "content-security-policy": [
    "default-src 'none'"
  ],
  "content-type": [
    "application/json; charset=utf-8"
  ],
  "date": [
    "Thu, 22 Mar 2018 20:17:53 GMT"
  ],
  "referrer-policy": [
    "origin-when-cross-origin, strict-origin-when-cross-origin"
  ],
  "server": [
    "GitHub.com"
  ],
  "status": [
    "403 Forbidden"
  ],
  "strict-transport-security": [
    "max-age=31536000; includeSubdomains; preload"
  ],
  "transfer-encoding": [
    "chunked"
  ],
  "x-content-type-options": [
    "nosniff"
  ],
  "x-frame-options": [
    "deny"
  ],
  "x-github-media-type": [
    "github.v3"
  ],
  "x-github-request-id": [
    "D3DF:1FD93:18156D5:1E99EB5:5AB40F71"
  ],
  "x-ratelimit-limit": [
    "60"
  ],
  "x-ratelimit-remaining": [
    "0"
  ],
  "x-ratelimit-reset": [
    "1521753177"
  ],
  "x-runtime-rack": [
    "0.011201"
  ],
  "x-xss-protection": [
    "1; mode=block"
  ]
}
    at createHttpError (/Applications/There.app/Contents/Resources/app.asar/node_modules/builder-util-runtime/src/httpExecutor.ts:31:10)
    at IncomingMessage.response.on (/Applications/There.app/Contents/Resources/app.asar/node_modules/builder-util-runtime/src/httpExecutor.ts:156:18)
    at emitNone (events.js:105:13)
    at IncomingMessage.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1045:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
From previous event:
    at CancellationToken.createPromise (/Applications/There.app/Contents/Resources/app.asar/node_modules/builder-util-runtime/src/CancellationToken.ts:51:5)
    at ElectronHttpExecutor.doApiRequest (/Applications/There.app/Contents/Resources/app.asar/node_modules/builder-util-runtime/src/httpExecutor.ts:81:30)
    at ElectronHttpExecutor.request (/Applications/There.app/Contents/Resources/app.asar/node_modules/builder-util-runtime/src/httpExecutor.ts:73:17)
    at GitHubProvider.httpRequest (/Applications/There.app/Contents/Resources/app.asar/node_modules/electron-updater/src/Provider.ts:26:26)
    at /Applications/There.app/Contents/Resources/app.asar/node_modules/electron-updater/src/GitHubProvider.ts:93:34
    at Generator.next (<anonymous>)
From previous event:
    at GitHubProvider.getLatestVersionString (/Applications/There.app/Contents/Resources/app.asar/node_modules/electron-updater/out/GitHubProvider.js:134:11)
    at /Applications/There.app/Contents/Resources/app.asar/node_modules/electron-updater/src/GitHubProvider.ts:49:30
From previous event:
    at GitHubProvider.getLatestVersion (/Applications/There.app/Contents/Resources/app.asar/node_modules/electron-updater/out/GitHubProvider.js:116:11)
    at /Applications/There.app/Contents/Resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:294:25
From previous event:
    at MacUpdater.getUpdateInfo (/Applications/There.app/Contents/Resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:336:11)
    at /Applications/There.app/Contents/Resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:298:35
    at Generator.next (<anonymous>)
From previous event:
    at MacUpdater.doCheckForUpdates (/Applications/There.app/Contents/Resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:368:11)
    at /Applica...
  File "/Applications/There.app/Contents/Resources/app.asar/main/updates.js", line 20, in updateApp
    await autoUpdater.checkForUpdates()
  File "/Applications/There.app/Contents/Resources/app.asar/main/updates.js", line 29, in module.exports
    updateApp()
  File "/Applications/There.app/Contents/Resources/app.asar/main/index.js", line 125, in App.app.on
    autoUpdate()
  File "/Applications/There.app/Contents/Resources/app.asar/main/updates.js", line 20, in updateApp
    await autoUpdater.checkForUpdates()
  File "/Applications/There.app/Contents/Resources/app.asar/main/updates.js", line 29, in module.exports
    updateApp()
...
(196 additional frame(s) were not displayed)

Error: Cannot parse releases feed: Error: Unable to find latest version on GitHub (https://api.github.com/repos/therepm/there-desktop/releases/latest), please ensure a production release exists: HttpError: 403 Forbidden
{
  "message": "API rate limit exceeded for 162.245.20.51. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)",
  "documentation_url": "https://developer.github.com/v3/#rate-limiting"
}
Headers: {
  "access-control-allow-origin": [
    "*"
  ],
  "access-control-expose-headers": [
    "ETag, Link, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval"
  ],
  "content-encoding": [
    "gzip"
  ],
  "content-security-policy": [
    "default-src 'none'"
  ],
  "content-type": [
    "application/json; charset=utf-8"
  ],
  "date": [
    "Thu, 22 Mar 2018 20:17:53 GMT"
  ],
  "referrer-policy": [
    "origin-when-cross-origin, strict-origin-when-cross-origin"
  ],
  "server": [
    "GitHub.com"
  ],
  "status": [
    "403 Forbidden"
  ],
  "strict-transport-security": [
    "max-age=31536000; includeSubdomains; preload"
  ],
  "transfer-encoding": [
    "chunked"
  ],
  "x-content-type-options": [
    "nosniff"
  ],
  "x-frame-options": [
    "deny"
  ],
  "x-github-media-type": [
    "github.v3"
  ],
  "x-github-request-id": [
    "D3DF:1FD93:18156D5:1E99EB5:5AB40F71"
  ],
  "x-ratelimit-limit": [
    "60"
  ],
  "x-ratelimit-remaining": [
    "0"
  ],
  "x-ratelimit-reset": [
    "1521753177"
  ],
  "x-runtime-rack": [
    "0.011201"
  ],
  "x-xss-protection": [
    "1; mode=block"
  ]
}
    at createHttpError (/Applications/There.app/Contents/Resources/app.asar/node_modules/builder-util-runtime/src/httpExecutor.ts:31:10)
    at IncomingMessage.response.on (/Applications/There.app/Contents/Resources/app.asar/node_modules/builder-util-runtime/src/httpExecutor.ts:156:18)
    at emitNone (events.js:105:13)
    at IncomingMessage.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1045:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
From previous event:
    at CancellationToken.createPromise (/Applications/There.app/Contents/Resources/app.asar/node_modules/builder-util-runtime/src/CancellationToken.ts:51:5)
    at ElectronHttpExecutor.doApiRequest (/Applications/There.app/Contents/Resources/app.asar/node_modules/builder-util-runtime/src/httpExecutor.ts:81:30)
    at ElectronHttpExecutor.request (/Applications/There.app/Contents/Resources/app.asar/node_modules/builder-util-runtime/src/httpExecutor.ts:73:17)
    at GitHubProvider.httpRequest (/Applications/There.app/Contents/Resources/app.asar/node_modules/electron-updater/src/Provider.ts:26:26)
    at /Applications/There.app/Contents/Resources/app.asar/node_modules/electron-updater/src/GitHubProvider.ts:93:34
    at Generator.next (<anonymous>)
From previous event:
    at GitHubProvider.getLatestVersionString (/Applications/There.app/Contents/Resources/app.asar/node_modules/electron-updater/out/GitHubProvider.js:134:11)
    at /Applications/There.app/Contents/Resources/app.asar/node_modules/electron-updater/src/GitHubProvider.ts:49:30
From previous event:
    at GitHubProvider.getLatestVersion (/Applications/There.app/Contents/Resources/app.asar/node_modules/electron-updater/out/GitHubProvider.js:116:11)
    at /Applications/There.app/Contents/Resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:294:25
From previous event:
    at MacUpdater.getUpdateInfo (/Applications/There.app/Contents/Resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:336:11)
    at /Applications/There.app/Contents/Resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:298:35
    at Generator.next (<anonymous>)
From previous event:
    at MacUpdater.doCheckForUpdates (/Applications/There.app/Contents/Resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:368:11)
    at /Applications/There.app/Contents/Resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:269:25
    at Generator.next (<anonymous>)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)
From previous event:
    at MacUpdater._checkForUpdates (/Applications/There.app/Contents/Resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:314:11)
    at MacUpdater.checkForUpdates (/Applications/There.app/Contents/Resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:218:35)
    at updateApp (/Applications/There.app/Contents/Resources/app.asar/main/updates.js:20:23)
    at module.exports (/Applications/There.app/Contents/Resources/app.asar/main/updates.js:29:5)
    at App.app.on (/Applications/There.app/Contents/Resources/app.asar/main/index.js:125:3)
    at emitTwo (events.js:130:20)
    at App.emit (events.js:213:7)
    at createHttpError (/Applications/There.app/Contents/Resources/app.asar/node_modules/builder-util-runtime/src/httpExecutor.ts:31:10)
    at IncomingMessage.response.on (/Applications/There.app/Contents/Resources/app.asar/node_modules/builder-util-runtime/src/httpExecutor.ts:156:18)
    at emitNone (events.js:105:13)
    at IncomingMessage.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1045:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
    at CancellationToken.createPromise (/Applications/There.app/Contents/Resources/app.asar/node_modules/builder-util-runtime/src/CancellationToken.ts:51:5)
    at ElectronHttpExecutor.doApiRequest (/Applications/There.app/Contents/Resources/app.asar/node_modules/builder-util-runtime/src/httpExecutor.ts:81:30)
    at ElectronHttpExecutor.request (/Applications/There.app/Contents/Resources/app.asar/node_modules/builder-util-runtime/src/httpExecutor.ts:73:17)
    at GitHubProvider.httpRequest (/Applications/There.app/Contents/Resources/app.asar/node_modules/electron-updater/src/Provider.ts:26:26)
    at /Applications/There.app/Contents/Resources/app.asar/node_modules/electron-updater/src/GitHubProvider.ts:93:34
    at Generator.next (<anonymous>)
    at GitHubProvider.getLatestVersionString (/Applications/There.app/Contents/Resources/app.asar/node_modules/electron-updater/out/GitHubProvider.js:134:11)
    at /Applications/There.app/Contents/Resources/app.asar/node_modules/electron-updater/src/GitHubProvider.ts:49:30
    at GitHubProvider.getLatestVersion (/Applications/There.app/Contents/Resources/app.asar/node_modules/electron-updater/out/GitHubProvider.js:116:11)
    at /Applications/There.app/Contents/Resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:294:25
    at MacUpdater.getUpdateInfo (/Applications/There.app/Contents/Resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:336:11)
    at /Applications/There.app/Contents/Resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:298:35
    at Generator.next (<anonymous>)
    at MacUpdater.doCheckForUpdates (/Applications/There.app/Contents/Resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:368:11)
    at /Applications/There.app/Contents/Resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:269:25
    at Generator.next (<anonymous>)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)
    at MacUpdater._checkForUpdates (/Applications/There.app/Contents/Resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:314:11)
    at MacUpdater.checkForUpdates (/Applications/There.app/Contents/Resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:218:35)
    at updateApp (/Applications/There.app/Contents/Resources/app.asar/main/updates.js:20:23)
    at module.exports (/Applications/There.app/Contents/Resources/app.asar/main/updates.js:29:5)
    at App.app.on (/Applications/There.app/Contents/Resources/app.asar/main/index.js:125:...
```

**Comment by DeltaStudioApp** [comment]
Have you solved this?
